[package]
name = "solana_test"
version = "0.1.0"
edition = "2021"
default-run = "solana_test"

[features]
default = []
zk = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git" }
getrandom = { version = "0.2", features = ["custom"] }

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# ZisK-specific target configuration
[target.riscv64ima-zisk-zkvm-elf]
rustflags = [
    "-C", "link-arg=-Tzisk-memory.x",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,--strip-all",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-static"
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"


