[package]
name = "solana_test"
version = "0.1.0"
edition = "2021"
default-run = "solana_test"

[features]
default = []
zk = []

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
getrandom = "0.2"
chrono = { version = "0.4", features = ["serde"] }

# Solana dependencies - pin to same 2.3.x line for compatibility
solana_rbpf = { version = "0.8.5", features = ["debugger"] }
solana-sdk = "=2.3.1"
solana-transaction-status = "=2.3.1"
solana-transaction-status-client-types = "=2.3.1"
solana-account-decoder = "=2.3.1"

# Cryptographic dependencies
bs58 = "0.5"
sha2 = "0.10"
sha3 = "0.10"
ed25519-dalek = "2.0"

# Utility dependencies
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
base64 = "0.21"
hex = "0.4"

# ZisK dependencies
ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git", package = "ziskos" }

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
bs58 = "0.5"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.21"

# ZisK-specific target configuration
[target.riscv64imac-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tzisk-memory.x",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,--strip-all",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-static"
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"


