[package]
name = "solana_test"
version = "0.1.0"
edition = "2021"

# ZisK guest program - compiled to RISC-V
[lib]
name = "solana_test"
crate-type = ["cdylib"]

# Binary target for testing (only when not building for ZisK)
[[bin]]
name = "solana_test"
path = "src/main.rs"
required-features = ["host-testing"]

[dependencies]
# ZisK zkVM integration
ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git" }

# Core Rust dependencies
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.0"
chrono = "0.4"
sha2 = "0.10"
hex = "0.4.3"
bs58 = "0.5"

# Remove Solana dependencies - not needed for ZisK guest program
# The BPF interpretation happens in pure Rust code compiled to RISC-V

[dev-dependencies]
# Testing dependencies
tokio = { version = "1.0", features = ["full"] }

# Build script dependencies
[build-dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1.0", features = ["full"] }
base64 = "0.21"
bs58 = "0.5"
chrono = "0.4"

# ================================================================
# FEATURES
# ================================================================

[features]
default = ["real-data"]

# Feature: Use real Solana data fetching (enabled by default)
real-data = []

# Feature: Enable debug logging in ZisK environment
debug-logging = []

# Feature: Enable development mode with faster, less secure proofs
dev-mode = []

# Feature: Enable host testing (for development, not ZisK)
host-testing = []

# Feature: Enable comprehensive testing
testing = []


