# ZisK Configuration File for Solana Test
# This file contains all ZisK-specific configuration options

[zisk]
# ZisK target configuration
target = "riscv64ima-zisk-zkvm-elf"
memory_layout = "zisk-memory.x"
heap_size = "64K"
stack_size = "8K"

# Build configuration
rustflags = [
    "-C", "link-arg=-Tzisk-memory.x",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,--strip-all",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-static"
]

# Feature flags
features = ["zk"]

# Cycle limits
max_cycles = 1000000
cycle_warning_threshold = 800000

# Memory constraints
max_memory = "64K"
max_accounts = 1000
max_account_data = 128

# Proof generation
proof_format = "bin"
input_file = "zk_input.bin"
output_file = "zk_proof.bin"
verification_enabled = true

# Performance settings
optimization_level = 3
lto_enabled = true
panic_abort = true

# Debug settings
debug_symbols = false
backtrace_enabled = false

# Integration settings
auto_proof_generation = true
auto_verification = true
cleanup_intermediate_files = false

# Monitoring
enable_metrics = true
enable_logging = true
log_level = "info"

# Advanced settings
custom_constraints = []
circuit_optimization = true
memory_alignment = 8
